MODEL:
    MODEL_NAME : "LR"
    MODEL_LAYERS: [2048,5270]

TRAIN:
    BATCH_SIZE : 10
    EPOCHS_COUNT : 250
    LEARNING_RATE : 0.001
    TRAIN_TF_RECORDS : "/data/data/train_example.tfrecord"

    EVAL_BATCH_SIZE : 5
    EVAL_TF_RECORDS : "/data/data/train_example.tfrecord"

TEST:
    BATCH_SIZE : 20
    TEST_TF_RECORDS : "/data/data/train_example.tfrecord"
    OUTPUT_CSV_PATH : "/data/outputs/LR_predict.csv"
