MODEL:
    MODEL_NAME : "NN2-Inception-2016-full-dataset-with-weights"
    MODEL_LAYERS: [2048,1024, 5270]

TRAIN:
    BATCH_SIZE : 256
    EPOCHS_COUNT : 50000
    LEARNING_RATE : 0.0001
    TRAIN_TF_RECORDS : "/data/data/train/split_8/tfrecords"

    EVAL_BATCH_SIZE : 3000
    EVAL_TF_RECORDS : "/data/data/train/split_8/eval.tfrecord"


TEST:
    BATCH_SIZE : 20000
    TEST_TF_RECORDS : "/data/data/test/tf_records/"
    OUTPUT_CSV_PATH : "/data/outputs/NN2-Inception-2016-full-dataset_predict.csv"
